// (C) Patricia Marklund, Anna Törngren, Sanna Evertsson, group: 10 (2023) 
// Work package 1 
// Exercise 3 
// Submission code: xxxxx (provided by your TA-s)

#define MAX_NUMBER 5

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
    int numGenerated;
    int numGuessed = 0;
    int deviation = 10;
    int numOfGuesses = 0;
    char answer;
   
    srand(time(0));    

    numGenerated = rand() % 100 + 1;

    printf("Random number: %d \n", numGenerated);

    printf("Enter the number you guess is the one generated by the computer: \n");
   
    do{
        scanf("%d", &numGuessed);

        if(numGenerated == numGuessed) {
            ++numOfGuesses;
            printf("You have guessed: %d times, and your guess is correct \n", numOfGuesses);
            break;        
        }
        if(numGenerated < numGuessed) {
            ++numOfGuesses;
            printf("Your guess is too high. Guess again \n");    
        }
        if(numGenerated > numGuessed) {
            ++numOfGuesses;
            printf("Your guess is too low. Guess again \n");
        }
        
    } while (numOfGuesses < MAX_NUMBER);

    if (numOfGuesses >= 4){
            printf("Do you want to try again? Answer with s or n: \n");
            scanf("%c", &answer);
            if(answer = getchar() == 'Y'){
                printf("Count should go to 0");
                numOfGuesses = 0;
            }else if(answer = getchar() == 'N') {
                printf("Program should stop");
            }
        }

    return 0;
   
}